version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: parameters_db
    ports: ["5132:5132"]
    volumes: ["db_data:/var/lib/postgressql/data"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      retries: 10
  api:
    build: .
    env_file: .env
    ports: ["3000:3000"]
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data: